name: Check

on:
  push:
    tags:
      - 'v0.*'
      - 'v1.*'
    branches:
      - 'master'
      - 'ci/*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache IDEA downloading
        id: cache-idea
        uses: actions/cache@v4
        with:
          path: ~/idea-IC-*
          key: ${{ runner.os }}-ideaIC-2024.3.1.1

      - name: Install IntelliJ IDEA
        if: steps.cache-idea.outputs.cache-hit != 'true'
        run: curl https://download.jetbrains.com/idea/ideaIC-2024.3.1.1.tar.gz -L | tar -xzf - -C ~

      - uses: actions/checkout@v3

      - name: Reformat
        run: ~/idea-IC-*/bin/format.sh -r -m *.kt,*.kts,*.java .
      - name: Check
        run: git diff --exit-code --color

